development:
  adapter: sqlserver
  mode: odbc
  dsn: Gefin
  database: gefin_final
  username: sa
  password: qwe123@

test:
  adapter: sqlserver
  mode: odbc
  dsn: Gefin
  database: gefin_test
  username: usuario_do_sql_server
  password: senha_do_sql_server

production:
  adapter: sqlserver
  mode: odbc
  dsn: Gefin
  database: gefin_production
  username: usuario_do_sql_server
  password: senha_do_sql_server
